server:
  port: 8080
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthFilter

        - id: athlete-service
          uri: lb://ATHLETE-SERVICE
          predicates:
            - Path=/athletes/**, /coaches/**, /diets/**
          filters:
            - JwtAuthFilter

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event/**, /meet/**
          filters:
            - JwtAuthFilter


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost